services:
  - type: web
    name: dropship-finder
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: dropship-db
    databaseName: dropship
    user: dropship
    region: frankfurt
